language: generic

addons:
  apt:
    packages:
    - lftp

after_success:
- scripts/deploy.sh

jobs:
  include:
  - stage: preview
    if: branch IN (master, devel)
    script:
    - echo "I'm testing..."
  - stage: production
    if: branch=master
    script:
    - echo "I'm publishing..."
