language: generic
addons:
  ssh_known_hosts: nyeuk.com
script:
  - chmod +x scripts/deploy.sh
after_success:
- bash scripts/deploy.sh
jobs:
  include:
  - stage: preview
    if: branch = develop
    script:
    - echo "I'm testing..."
  - stage: production
    if: branch = master
    script:
    - echo "I'm publishing..."
before_install:
- openssl aes-256-cbc -K $encrypted_6c332d22961c_key -iv $encrypted_6c332d22961c_iv
  -in .travis/nyeuk_travis_deploy.enc -out .travis/nyeuk_travis_deploy -d