language: generic
addons:
  apt:
    packages:
    - lftp
after_success:
- scripts/deploy.sh
jobs:
  include:
  - stage: preview
    if: branch IN (master, develop)
    script:
    - echo "I'm testing..."
  - stage: production
    if: branch = master
    script:
    - echo "I'm publishing..."
before_install:
- openssl aes-256-cbc -K $encrypted_6c332d22961c_key -iv $encrypted_6c332d22961c_iv
  -in .travis/nyeuk_travis_deploy.enc -out .travis/nyeuk_travis_deploy -d